CREATE TABLE DEPT(
   D_NUM NUMBER,
   D_NAME VARCHAR2(30) NOT NULL,
   D_LEVEL NUMBER CHECK (D_LEVEL BETWEEN 0 AND 3),
   D_COLOR VARCHAR2(10) NOT NULL,
   D_UPPERLEVEL NUMBER NOT NULL,
   PRIMARY KEY(D_NUM)   
);

SELECT D_NUM, D_NAME, D_LEVEL, D_COLOR, D_UPPERLEVEL
FROM DEPT
ORDER BY D_LEVEL, D_NUM;

select * from dept;